// js/data.js

// Exporte les données des véhicules pour qu'elles puissent être utilisées par d'autres modules.
export const vehicleData = [
    { name: "GIO Motocross GX70", category: "essence", type: "Motocross", priceRange: "899 $- 1 299$", keyTakeaway: "Modèle d'entrée de gamme très populaire, souvent en rupture de stock à bas prix. Le prix de 1 299 $ semble être le nouveau standard.", vendors: [ { name: "Mic Performance", price: 869.00, status: "Épuisé" }, { name: "Turbo Kids", price: 899.95, status: "Épuisé" }, { name: "Vélorock Electrik", price: 1299.00, status: "En stock" } ] },
    { name: "GIO Motocross GX110", category: "essence", type: "Motocross", priceRange: "1 249 $- 1 399$", keyTakeaway: "Le prix est stable. La promotion de Mic Performance à 1 249 $ en fait l'option la plus attractive.", vendors: [ { name: "Mic Performance", price: 1249.00, status: "Stock bas" }, { name: "Kids on Wheelz", price: 1392.95, status: "En stock" }, { name: "TTC Motorsports", price: 1399.00, status: "En stock" }, { name: "Vélorock Electrik", price: 1499.00, status: "En stock" } ] },
    { name: "GIO Motocross VM 125 PREMIUM", category: "essence", type: "Motocross", priceRange: "1 899 $- 1 999$", keyTakeaway: "Prix très stable. Il se positionne comme un modèle premium.", vendors: [ { name: "Motosport Mauricie", price: 1899.00, status: "En stock" }, { name: "MIC Performance", price: 1899.00, status: "Stock bas" }, { name: "Gio Retail", price: 1999.00, status: "En stock" } ] },
    { name: "GIO Blazer 110B", category: "essence", type: "VTT", priceRange: "999 $- 1 045$", keyTakeaway: "Le 110B reste le produit d'appel sous la barre des 1000 $, bien que souvent en rupture de stock.", vendors: [ { name: "Gio Retail", price: 999.00, status: "Épuisé" }, { name: "ATV Edmonton", price: 1045.00, status: "En stock" } ] },
    { name: "GIO Blazer 110P", category: "essence", type: "VTT", priceRange: "1 245 $- 1 299$", keyTakeaway: "Montée en gamme claire par rapport au 110B.", vendors: [ { name: "Kids on Wheelz", price: 1245.98, status: "En stock" }, { name: "Gio Online Sales", price: 1299.00, status: "En stock" } ] },
    { name: "GIO Blazer 110H", category: "essence", type: "VTT", priceRange: "1 499 $", keyTakeaway: "Modèle utilitaire haut de gamme de la série 110cc.", vendors: [ { name: "Gio Retail", price: 1499.00, status: "En stock" }, { name: "Alberta Powersports", price: 1499.99, status: "En stock" } ] },
    { name: "GIO Blazer 125D", category: "essence", type: "VTT", priceRange: "1 399 $- 1 465$", keyTakeaway: "VTT utilitaire de milieu de gamme très compétitif.", vendors: [ { name: "Turbo Kids", price: 1399.95, status: "En stock" }, { name: "Gio Online Sales", price: 1450.00, status: "En stock" }, { name: "ATV Edmonton", price: 1465.00, status: "En stock" } ] },
    { name: "GIO Blazer 125P", category: "essence", type: "VTT", priceRange: "1 399 $- 1 899$", keyTakeaway: "Modèle sport semi-automatique. Le prix de Gio Retail est exceptionnellement bas.", vendors: [ { name: "Gio Retail", price: 1399.00, status: "En stock" }, { name: "ATV Edmonton", price: 1675.00, status: "En stock" }, { name: "Kids on Wheelz", price: 1899.99, status: "En stock" } ] },
    { name: "GIO Blazer 125S", category: "essence", type: "VTT", priceRange: "1 599 $- 1 865$", keyTakeaway: "VTT sportif automatique, concurrent direct du Tao Raptor.", vendors: [ { name: "Turbo Kids", price: 1599.95, status: "En stock" }, { name: "Gio Retail", price: 1799.00, status: "En stock" }, { name: "ATV Edmonton", price: 1865.00, status: "En stock" } ] },
    { name: "GIO Blazer 125HS PREMIUM", category: "essence", type: "VTT", priceRange: "1 949 $- 2 275$", keyTakeaway: "Le luxe «tout inclus» de la série Blazer, justifiant son prix élevé.", vendors: [ { name: "MIC Performance", price: 1949.00, status: "En stock" }, { name: "TTC Motorsports", price: 1999.00, status: "En stock" }, { name: "Gio Retail", price: 2099.00, status: "En stock" }, { name: "ATV Edmonton", price: 2275.00, status: "En stock" } ] },
    { name: "Motocross E-FLASH", category: "electrique", type: "Motocross", priceRange: "759 $- 799$", keyTakeaway: "Produit d'appel unique, sans concurrence directe dans sa gamme de prix.", vendors: [ { name: "MIC Performance", price: 759.00, status: "En stock" }, { name: "EZ Rides", price: 799.00, status: "En stock" }, { name: "Turbo Kids", price: 799.95, status: "En stock" } ] },
    { name: "VTT Minitron (eQuad S)", category: "electrique", type: "VTT", priceRange: "699 $- 799$", keyTakeaway: "Le VTT électrique le plus abordable, idéal pour les très jeunes enfants.", vendors: [ { name: "AutoHebdo", price: 699.00, status: "En stock" }, { name: "Gio Retail", price: 799.00, status: "En stock" } ] },
    { name: "VTT Manteray (eQuad M)", category: "electrique", type: "VTT", priceRange: "679 $- 899$", keyTakeaway: "Se situe entre le Minitron et les VTT 800W plus coûteux.", vendors: [ { name: "Turbo Kids", price: 679.95, status: "En stock" }, { name: "ATV Edmonton", price: 845.00, status: "En stock" }, { name: "AutoHebdo", price: 899.00, status: "En stock" } ] },
    { name: "VTT Optimus (eQuad X)", category: "electrique", type: "VTT", priceRange: "789 $- 899$", keyTakeaway: "Ce VTT électrique de 800W est une étape au-dessus du Manteray. Il est idéal pour les jeunes enfants de 3 à 8 ans.", vendors: [ { name: "MIC Performance", price: 789.00, status: "En stock" }, { name: "Vélorock Electrik", price: 899.00, status: "En stock" } ] },
    { name: "VTT Tornado", category: "electrique", type: "VTT", priceRange: "899 $", keyTakeaway: "Prix très stable. Référence du marché pour les VTT 800W.", vendors: [ { name: "AutoHebdo", price: 899.00, status: "En stock" }, { name: "Gio Retail", price: 899.00, status: "En stock" } ] },
    { name: "VTT Torpedo", category: "electrique", type: "VTT", priceRange: "994 $- 1 099$", keyTakeaway: "Point d'entrée pour la puissance 1000W, le rendant très attractif.", vendors: [ { name: "Kids On Wheelz", price: 994.94, status: "En stock" }, { name: "Gio Retail", price: 999.00, status: "En stock" }, { name: "Red Deer", price: 1099.00, status: "En stock" } ] },
    { name: "VTT Devastator (eQuad Q)", category: "electrique", type: "VTT", priceRange: "1 149 $- 1 299$", keyTakeaway: "Modèle 1200W/48V puissant, un cran au-dessus du Torpedo.", vendors: [ { name: "MIC Performance", price: 1149.00, status: "En stock" }, { name: "Turbo Kids", price: 1169.95, status: "En stock" }, { name: "Gio Retail", price: 1255.00, status: "En stock" } ] },
    { name: "VTT Juventus", category: "electrique", type: "VTT", priceRange: "1 699 $- 1 899$", keyTakeaway: "Haut de gamme 1000W/60V pour ados, justifié par sa puissance et son design.", vendors: [ { name: "Gio Retail", price: 1699.00, status: "En stock" }, { name: "Turbo Kids", price: 1699.95, status: "En stock" }, { name: "Red Deer", price: 1899.00, status: "En stock" } ] },
    { name: "VTT Megatron Premium", category: "electrique", type: "VTT", priceRange: "1 799 $- 1 999$", keyTakeaway: "Le fleuron de la gamme électrique (1500W/60V), destiné aux ados et adultes.", vendors: [ { name: "AutoHebdo", price: 1799.00, status: "En stock" }, { name: "Edmonton ATV", price: 1995.00, status: "En stock" }, { name: "Kids on Wheelz", price: 1999.98, status: "En stock" } ] },
];
